// Mocks generated by Mockito 5.4.4 from annotations
// in submission_1_restaurant_app/test/restaurant_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:submission_1_restaurant_app/data/api/api_service.dart' as _i2;
import 'package:submission_1_restaurant_app/data/model/customer_review.dart'
    as _i6;
import 'package:submission_1_restaurant_app/data/model/restaurant.dart' as _i5;
import 'package:submission_1_restaurant_app/provider/restaurants_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestaurantsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantsProvider extends _i1.Mock
    implements _i3.RestaurantsProvider {
  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  List<_i5.Restaurant> get restaurantsResult => (super.noSuchMethod(
        Invocation.getter(#restaurantsResult),
        returnValue: <_i5.Restaurant>[],
        returnValueForMissingStub: <_i5.Restaurant>[],
      ) as List<_i5.Restaurant>);

  @override
  List<_i6.CustomerReview> get customerReviewResult => (super.noSuchMethod(
        Invocation.getter(#customerReviewResult),
        returnValue: <_i6.CustomerReview>[],
        returnValueForMissingStub: <_i6.CustomerReview>[],
      ) as List<_i6.CustomerReview>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<dynamic> fetchAllRestaurants() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllRestaurants,
          [],
        ),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> fetchDetailRestaurant({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDetailRestaurant,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  void searchRestaurants(String? query) => super.noSuchMethod(
        Invocation.method(
          #searchRestaurants,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
